apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: logging
spec:
  selector:
    app: prometheus
  ports:
    - name: web
      port: 9090
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: logging
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.30.0
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
          ports:
            - name: web
              containerPort: 9090
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-storage
          emptyDir: {}
        - name: prometheus-config
          configMap:
            name: prometheus-config